### PR TITLE
Do not require charset=utf-8 for JSON

### LINKED ISSUE #39: Charset is not required for JSON
Per [JSON Interchange format](https://tools.ietf.org/html/rfc7159), `charset` isn't needed for JSON as it can be assumed to be in UTF-8.

The JSON response matcher thus doesn't need to enforce `charset=utf-8` even when the response contains non-ASCII characters.

### PR DESCRIPTION
**Pull request by koterpillar**
Per [JSON Interchange format](https://tools.ietf.org/html/rfc7159), `charset` isn't needed for JSON as it can be assumed to be in UTF-8.

The JSON response matcher thus doesn't need to enforce `charset=utf-8` even when the response contains non-ASCII characters.

Fixes #39.

### CODE REVIEW

**Comment by sol** [comment]
Sorry for the late reply, and thank you for bringing this up.

Apparently specifying a `charset` is not only redundant, but even illegal according to the content type registration.

So what do we actually want to do here? I think long-term we want to reject everything about `application/json`. As `hspec` does not provide a mechanism to issue warnings, we may do that change even now, without giving users a grace period.

Users that want to test nonstandard behavior are still free to specify their own expected headers.

**Comment by sol** [comment]
http://www.iana.org/assignments/media-types/application/json

**Comment by koterpillar** [comment]
That makes everything even easier. The code now only accepts `application/json` and doesn't bring in new dependencies.

**Comment by sol** [comment]
I went for an even simpler solution using `<:>`.

**Pull request closed without merging**
